carts/urls.py
from django.conf.urls import url

from .views import (
   cart_home,
   cart_update,
    checkout_home,

)

urlpatterns = [

    url(r'^$', cart_home, name='home'),
    url(r'^update/$',cart_update, name='update'),
    url(r'^checkout/$',checkout_home, name='checkout'),
]

ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import home_page,about_page,contact_page,my_orders
from accounts.views import login_page, register_page,logout_view, guest_register_view
from django.conf import settings
from django.conf.urls.static import static
#from django.contrib.auth.views import LogoutView
from products.views import add_product

#from comments.views import CommentLikeToggle
from products.views import  ProductListView





urlpatterns = [
    url(r'^$',  ProductListView.as_view(), name ='home'),
    url(r'^about/$', about_page, name ='about'),
    url(r'^contact/$', contact_page, name ='contact'),
    url(r'^orders/$',my_orders, name ='my_orders'),
    # url(r'^orders/(?P<pk>\d+)/update/$', request_update, name='book_update'),
    url(r'^login/$', login_page, name ='login'),
    url(r'^register/guest$', guest_register_view, name ='guest_register'),
    url(r'^logout/$',logout_view, name ='logout'),
    url(r'^register/$', register_page, name ='register'),
    url(r'^products/',include("products.urls" , namespace='products')),
    url(r'^product_requests/',include("product_requests.urls" , namespace='product_requests')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^accounts/', include("accounts.urls", namespace='accounts')),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^admin/', admin.site.urls),
    url(r'^add_product/$', add_product, name = 'add_product'),
    url(r'^requests/', include("requests.urls", namespace='requests')),
    url(r'^profile/', include("userprofile.urls", namespace='userprofile')),
    url(r'^friends/', include("friends.urls", namespace='friends')),

]

if settings.DEBUG :
    urlpatterns = urlpatterns +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product_requests/urls.py
from django.conf.urls import url

from .views import (
        sentrequest,


        )

urlpatterns = [
    url(r'^sent/$', sentrequest, name='sentrequest'),
    ]

requests/urls.py
from django.conf.urls import url

from .views import (

    requests_home,
    friend_request,
    PastRequests

)

urlpatterns = [

    url(r'^$', requests_home, name='home'),
    url(r'^friend_request/$', friend_request, name='friend_request'),
    url(r'^past_request/$', PastRequests.as_view(), name='past_requests'),
    url(r'^past_request_cancel/(?P<id>\d+)/$', PastRequests.as_view(), name='past_request_cancel'),
]

userprofile/urls.py
from django.conf.urls import url

from .views import (

        my_profile,
        my_tasks,
        task_requests,
        #ProfileDetailSlugView,
        friend_requests,
        my_friends,
        profile_detail,
        friend_profile_about,
        friend_profile_friends,
        friend_profile_task_history,
        friend_profile_task,

)

urlpatterns = [
    url(r'^$',my_profile , name='my_profile'),
    url(r'^my_tasks/$',my_tasks , name='my_tasks'),
    url(r'^task_requests/$',task_requests , name='task_requests'),
    url(r'^(?P<slug>[\w-]+)/$',profile_detail, name = 'profile_detail'),
    url(r'^friend_request/$',friend_requests , name='friend_requests'),
    url(r'^my_friends/$',my_friends , name='my_friends'),
    url(r'^(?P<slug>[\w-]+)/about/$',friend_profile_about, name = 'friend_profile_about'),
    url(r'^(?P<slug>[\w-]+)/tasks/$',friend_profile_task, name = 'friend_profile_task'),
    url(r'^(?P<slug>[\w-]+)/task_history/$',friend_profile_task_history, name = 'friend_profile_task_history'),
    url(r'^(?P<slug>[\w-]+)/friends/$',friend_profile_friends, name = 'friend_profile_friends'),



]

product_requests/models.py
from django.db import models
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from products.models import Product
# Create your models here.
#
#
User = settings.AUTH_USER_MODEL



class Product_Request(models.Model):
    sender        = models.ForeignKey(User, null=True, blank=True)
    product       = models.ForeignKey(Product, blank=True, null=True)
    reciever      = models.CharField(max_length=1200, blank=True, null=True)
    from_date     = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    till_date     = models.DateTimeField(null=True, blank=True)

    #product_owner = models.ForeignKey(Product.user, blank= True, null= True)

    def __str__(self):
        return str(self.product)

    # def clean_till_date(self):
    #     email = self.cleaned_data.get("email")
    #     if ((till_date - from_date) > 3):
    #         raise forms.ValidationError("This product cannot be shared for more than 3 days ")
    #     return email

def request_pre_save_receiver(sender, instance, *args, **kwargs):
    product_name = instance.product
    product = Product.objects.get_by_title(product_name)
    user = product.user
    instance.reciever = user


pre_save.connect(request_pre_save_receiver, sender=Product_Request)

userprofile/models.py
import os
import random
from django.db import models
from accounts.models import User
from requests.models import Requests
from products.models import Product
from django.conf import settings
#User = settings.AUTH_USER_MODEL
from ecommerce.utils import unique_slug_generator_for_user
from django.db.models.signals import pre_save
from django.core.urlresolvers import reverse




def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext

def upload_image_path(instance, filename):
    # print(instance)
    #print(filename)
    new_filename = random.randint(1,3910209312)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "products/{new_filename}/{final_filename}".format(
            new_filename=new_filename,
            final_filename=final_filename
            )


class Userprofile(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    email =  models.CharField(max_length=120,  null=True, blank=True)
    full_name = models.CharField(max_length=120,  null=True, blank=True)
    image = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    phone = models.CharField(max_length=12)
    products =  models.ManyToManyField(Product, blank=True)
    slug = models.SlugField(blank=True, unique=True)
    friends = models.ManyToManyField(User, blank=True, related_name='friends')



    #recieved_requests = models.ManyToManyField(Requests, blank=True)
    #sent_requests = models.ManyToManyField(Requests, blank=True)


    def __str__(self):
        return self.user.get_full_name()

    def get_absolute_url(self):
        return reverse('userprofile', kwargs={'slug': self.slug})

def full_name_pre_save_reciever(sender, instance, *args, **kwargs):
    user= instance.user
    instance.full_name = user.full_name

def email_pre_save_reciever(sender, instance, *args, **kwargs):
    user= instance.user
    instance.email = user.email


def profile_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator_for_user(instance)

pre_save.connect(full_name_pre_save_reciever, sender=Userprofile )
pre_save.connect(profile_pre_save_receiver, sender=Userprofile)
pre_save.connect(email_pre_save_reciever, sender=Userprofile )



class Profile(models.Model):
    user= models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default = 'default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user}Profile'







# def upload_product_file_loc(instance, filename):
#     slug = instance.product.slug
#     #id_ = 0
#     id_ = instance.id
#     if id_ is None:
#         Klass = instance.__class__
#         qs = Klass.objects.all().order_by('-pk')
#         if qs.exists():
#             id_ = qs.first().id + 1
#         else:
#             id_ = 0
#     if not slug:
#         slug = unique_slug_generator(instance.product)
#     location = "product/{slug}/{id}/".format(slug=slug, id=id_)
#     return location + filename #"path/to/filename.mp4"

userprofile/forms.py
from django import forms
from django.contrib.auth import get_user_model



User = get_user_model()





class FriendRequestForm(forms.Form):
    CHOICES=[('accepted','accept'),
             ('rejected','reject')]

    request_status = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)

    #
    # user = models.ForeignKey(User, null=True, blank=True)
    # full_name = models.CharField(max_length=120,  null=True, blank=True)
    # image = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    # phone = models.CharField(max_length=

class EditProfileForm(forms.Form):

    full_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Name"

            }
        )
    )
    phone = forms.DecimalField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Phone #"

            }
        )
    )

    # image = forms.ImageField()

product_requests/views.py
from django.shortcuts import render
from .models import Product_Request
from django.conf import settings
from products.models import Product
# Create your views here.

User = settings.AUTH_USER_MODEL

def recievedrequest(request):
    requests = Product_Request.objects.all()
    context = {
        'requests': requests,
    }
    return render(request,'recieved_request.html',context)


def sentrequest(request):
    requests = Product_Request.objects.filter(sender = request.user)
    for request_ in requests:
        print(request_.product.user)
    context = {
    }
    return render(request,'product_requests/recieved_request.html',context)

userprofile/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import get_user_model
from django.contrib import messages
from products.models import Product
from django.conf import settings
from requests.models import Requests, friend_request
from django.views.generic import DetailView
from .models import Userprofile
from django.http import Http404, HttpResponse, HttpResponseRedirect
from .forms import FriendRequestForm, EditProfileForm
from accounts.models import User
from django.core.urlresolvers import reverse



user = settings.AUTH_USER_MODEL
def my_profile(request):
    edit_profile_form = EditProfileForm(request.POST)

    context = {
        'form': edit_profile_form,
    }
    if edit_profile_form.is_valid():
        full_name = edit_profile_form.cleaned_data.get('full_name')
        phone = edit_profile_form.cleaned_data.get('phone')
        account = User.objects.filter( email = request.user.email)[0]
        profile = Userprofile.objects.filter( email = request.user.email)[0]

        account.full_name = full_name
        account.save()
        profile.full_name = full_name
        profile.phone= phone
        profile.save()

    return render(request,'userprofile/myprofile.html', context)
def task_requests(request):
    user = request.user
    req_qs = Requests.objects.get_by_user(user)
    new_req_qs = list(dict.fromkeys(req_qs))
    print(new_req_qs)
    context = {
        'object_qs': new_req_qs,
    }

    return render(request, 'userprofile/product_requests.html', context)

def my_tasks(request):
    user = request.user
    product_qs = Product.objects.get_by_userp(user)
    task_no_repitition_qs = []
    for object in product_qs:
        if object in task_no_repitition_qs==False:
            task_no_repitition_qs.append(object)

    context = {
        'object_qs' : task_no_repitition_qs,
    }
    return render(request,'userprofile/my_products.html', context)


def friend_requests(request):
    user = request.user

    friend_request_qs = friend_request.objects.filter(user=user)
    pending_request_qs = friend_request_qs.filter(status='pending')
    friend_request_form = FriendRequestForm(request.POST)
    context = {
        'object_qs':pending_request_qs,
        'form': friend_request_form,
    }
    if friend_request_form.is_valid():
        request_status = friend_request_form.cleaned_data.get('request_status')
        friend_name  = friend_request_form.cleaned_data.get('name')
        friend = friend_request.objects.filter(user=friend_name)
        print(friend)



    return render(request, 'userprofile/my_friend_requests.html', context)


def my_friends(request):
    user = request.user
    friend_request_qs = friend_request.objects.filter(user = user)
    accepted_request_qs = friend_request_qs.filter(status='accepted')



    print(accepted_request_qs)
    context = {
        'object_qs' : accepted_request_qs ,
    }
    return render(request,'userprofile/my_friends.html', context)



def profile_detail(request,slug):

    userprofile = get_object_or_404(Userprofile, slug=slug)
    context = {
        'userprofile':userprofile,
    }
    return render(request,'userprofile/friends_profile.html', context)

def friend_profile_about(request,slug):
    userprofile = get_object_or_404(Userprofile, slug=slug)
    print(request.path)
    context= {
        'userprofile': userprofile,
    }
    return render(request, 'userprofile/friends_profile.html', context)

def friend_profile_friends(request,slug):
    userprofile = get_object_or_404(Userprofile, slug=slug)
    print(request.path)
    context= {
        'userprofile': userprofile,
    }
    return render(request, 'userprofile/friends_profile.html', context)

def friend_profile_task_history(request,slug):
    userprofile = get_object_or_404(Userprofile, slug=slug)
    print(request.path)
    context= {
        'userprofile': userprofile,
    }
    return render(request, 'userprofile/friends_profile.html', context)


def friend_profile_task(request,slug):
    userprofile = get_object_or_404(Userprofile, slug=slug)
    print(request.path)
    context= {
        'userprofile': userprofile,
    }
    return render(request, 'userprofile/friends_profile.html', context)




# class ProfileDetailSlugView(DetailView):
#
#     queryset = Userprofile.objects.all()
#     template_name = "userprofile/profile.html"
#
#
#
#
#
#     def get_context_data(self, *args, **kwargs):
#
#         context = super(ProfileDetailSlugView, self).get_context_data(*args, **kwargs)
#         return context
#
#
#
#
#     def get_object(self, *args, **kwargs):
#         request = self.request
#         print(request)
#         slug = self.kwargs.get('slug')
#
#                 # instance = get_object_or_404(Product, slug=slug, active=True)
#         try:
#             instance = Userprofile.objects.get(slug=slug)
#         except Userprofile.DoesNotExist:
#             raise Http404("Not found..")
#         except Userprofile.MultipleObjectsReturned:
#             qs = Userprofile.objects.filter(slug=slug)
#             instance = qs.first()
#         except:
#             raise Http404("Uhhmmm ")
#         return instance

userprofile/templates/userprofile/accountsbase.html
{% extends 'base.html' %}

{% block content %}
{% url 'userprofile:my_profile' as profile_url %}
{% url 'userprofile:my_tasks' as tasks_url %}
{% url 'userprofile:task_requests' as task_requests %}
{% url 'userprofile:sent' as sent_url %}
{% url 'userprofile:recieved' as recieved_url %}
{% url 'userprofile:friend_requests' as friend_request_url %}
{% url 'userprofile:my_friends' as  my_friends_url %}
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

<!------ Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

<!------ Include the above in your HEAD tag ---------->

<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>


<hr>
<div class="container bootstrap snippet">
    <div class="row">
  		<div class="col-sm-10"><h1>{{ request.user.full_name }}</h1></div>
    	<div class="col-sm-2"><a href="{{ request.user.image.url }}" class="pull-right"><img title="profile image" class="img-circle img-responsive" src="http://www.gravatar.com/avatar/28fd20ccec6865e2d5f0e1f4446eb7bf?s=100"></a></div>
    </div>
    <div class="row">
  		<div class="col-sm-3"><!--left col-->


      <div class="text-center">
        <img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="avatar img-circle img-thumbnail" alt="avatar">
        <h6>Upload a different photo...</h6>
        <input type="file" class="text-center center-block file-upload">
      </div></hr><br>


          <div class="panel panel-default">
            <div class="panel-heading">Contact<i class="fa fa-link fa-1x"></i></div>
            <div class="panel-body"><a href="http://bootnipets.com">bootnipets.com</a></div>
          </div>


          <ul class="list-group">
            <li class="list-group-item text-muted">Activity <i class="fa fa-dashboard fa-1x"></i></li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Likes</strong></span> 13</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Tasks</strong></span> 37</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Friends</strong></span> 78</li>
          </ul>

          <div class="panel panel-default">
            <div class="panel-heading">Social Media</div>
            <div class="panel-body">
            	<i class="fa fa-facebook fa-2x"></i> <i class="fa fa-github fa-2x"></i> <i class="fa fa-twitter fa-2x"></i> <i class="fa fa-pinterest fa-2x"></i> <i class="fa fa-google-plus fa-2x"></i>
            </div>
          </div>

        </div><!--/col-3-->
    	<div class="col-sm-9">
            <ul class="nav ">

                <li class="nav-item {% if request.path == profile_url %} active {% endif %}">
                    <a class="nav-link" href="{{profile_url}}">Edit Profile</a>
                </li>
                <li class="nav-item">
                   <li class="nav-item" {% if request.path ==  my_friends_url %} active {% endif %} >
                    <a class="nav-link" href="{{  my_friends_url }}">My Friends</a>
                </li>
                </li>
                <li class="nav-item" {% if request.path == friend_request_url %} active {% endif %} >
                    <a class="nav-link" href="{{ friend_request_url }}">Friend Requests</a>
                </li>
                <li class="nav-item {% if request.path == tasks_url %} active {% endif %}">
                    <a class="nav-link" href="{{tasks_url}}">My Tasks</a>
                </li>
                <li class="nav-item {% if request.path == task_requests %} active {% endif %}">
                    <a class="nav-link" href="{{task_requests}}">Task History</a>
                </li>
              </ul>
        <div class="tab-content">
            <div class="container">
                {% block profilecontent %}{% endblock %}
             </div>
        </div>


          </div><!--/tab-content-->

        </div><!--/col-9-->
    </div>
{% endblock %}

userprofile/templates/userprofile/friend-request.html
<form method="POST" action="{% url 'requests:home' %}" class="form">{% csrf_token %}
    <input type="hidden" name="product" value="{{ user.id }}"/>

            <button type="submit" class="btn btn-success ">Send Friend Request</button>

</form>

userprofile/templates/userprofile/friend_request_profile.html
{% extends 'base.html' %}

{% block content %}
{% url 'userprofile:my_profile' as profile_url %}
{% url 'userprofile:my_tasks' as tasks_url %}
{% url 'userprofile:task_requests' as task_requests %}
{% url 'userprofile:sent' as sent_url %}
{% url 'userprofile:recieved' as recieved_url %}
{% url 'userprofile:friend_requests' as friend_request_url %}
{% url 'userprofile:my_friends' as  my_friends_url %}
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

<!------ Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

<!------ Include the above in your HEAD tag ---------->

<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>


<hr>
<div class="container bootstrap snippet">
    <div class="row">
  		<div class="col-sm-10"><h1>{{ userprofile.full_name }}</h1></div>
    	<div class="col-sm-2"><a href="{{ userprofile.image}}" class="pull-right"></a></div>
    </div>
{#    <div class="row">#}
{#  		<div class="col-sm-3"><!--left col-->#}
{##}
{##}
{#      <div class="text-center">#}
{#        <img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="avatar img-circle img-thumbnail" alt="avatar">#}
{#        <h6>Upload a different photo...</h6>#}
{#        <input type="file" class="text-center center-block file-upload">#}
{#      </div></hr><br>#}
{##}
{##}
{#          <div class="panel panel-default">#}
{#            <div class="panel-heading">Contact<i class="fa fa-link fa-1x"></i></div>#}
{#            <div class="panel-body"><a href="http://bootnipets.com">bootnipets.com</a></div>#}
{#          </div>#}
{##}
{##}
{#          <ul class="list-group">#}
{#            <li class="list-group-item text-muted">Activity <i class="fa fa-dashboard fa-1x"></i></li>#}
{#            <li class="list-group-item text-right"><span class="pull-left"><strong>Likes</strong></span> 13</li>#}
{#            <li class="list-group-item text-right"><span class="pull-left"><strong>Tasks</strong></span> 37</li>#}
{#            <li class="list-group-item text-right"><span class="pull-left"><strong>Friends</strong></span> 78</li>#}
{#          </ul>#}
{##}
{#          <div class="panel panel-default">#}
{#            <div class="panel-heading">Social Media</div>#}
{#            <div class="panel-body">#}
{#            	<i class="fa fa-facebook fa-2x"></i> <i class="fa fa-github fa-2x"></i> <i class="fa fa-twitter fa-2x"></i> <i class="fa fa-pinterest fa-2x"></i> <i class="fa fa-google-plus fa-2x"></i>#}
{#            </div>#}
{#          </div>#}

        </div><!--/col-3-->
    	<div class="col-sm-9">
            <ul class="nav ">

            <li class="nav-item">
                <li class="nav-item" {% if request.path ==  my_friends_url %} active {% endif %} >
                    <a class="nav-link" href="{{  my_friends_url }}">About</a>
                </li>

                </li>
                <li class="nav-item {% if request.path == tasks_url %} active{% endif %}">
                    <a class="nav-link" href="{{tasks_url}}">Tasks</a>
                </li>

              </ul>
        <div class="tab-content">
            <div class="container">
                {% block profilecontent %}{% endblock %}
             </div>
        </div>


          </div><!--/tab-content-->

        </div><!--/col-9-->
    </div>
{% endblock %}

userprofile/templates/userprofile/friends_profile.html
{% extends 'base.html' %}

{% block content %}
{% url 'userprofile:friend_profile_about' as about_url %}
{% url 'userprofile:friend_profile_task' as task_url %}
{% url 'userprofile:friend_profile_task_history' as task_history_url %}
{% url 'userprofile:friend_profile_friends' as friends_url %}

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

<!------ Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

<!------ Include the above in your HEAD tag ---------->

<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>


<hr>
<div class="container bootstrap snippet">
    <div class="row">
  		<div class="col-sm-10"><h1>{{ userprofile.full_name }}</h1></div>
    	<div class="col-sm-2"><a href="{{ userprofile.image}}" class="pull-right"></a></div>
    </div>
{#    <div class="row">#}
{#  		<div class="col-sm-3"><!--left col-->#}
{##}
{##}
{#      <div class="text-center">#}
{#        <img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="avatar img-circle img-thumbnail" alt="avatar">#}
{#        <h6>Upload a different photo...</h6>#}
{#        <input type="file" class="text-center center-block file-upload">#}
{#      </div></hr><br>#}
{##}
{##}
{#          <div class="panel panel-default">#}
{#            <div class="panel-heading">Contact<i class="fa fa-link fa-1x"></i></div>#}
{#            <div class="panel-body"><a href="http://bootnipets.com">bootnipets.com</a></div>#}
{#          </div>#}
{##}
{##}
{#          <ul class="list-group">#}
{#            <li class="list-group-item text-muted">Activity <i class="fa fa-dashboard fa-1x"></i></li>#}
{#            <li class="list-group-item text-right"><span class="pull-left"><strong>Likes</strong></span> 13</li>#}
{#            <li class="list-group-item text-right"><span class="pull-left"><strong>Tasks</strong></span> 37</li>#}
{#            <li class="list-group-item text-right"><span class="pull-left"><strong>Friends</strong></span> 78</li>#}
{#          </ul>#}
{##}
{#          <div class="panel panel-default">#}
{#            <div class="panel-heading">Social Media</div>#}
{#            <div class="panel-body">#}
{#            	<i class="fa fa-facebook fa-2x"></i> <i class="fa fa-github fa-2x"></i> <i class="fa fa-twitter fa-2x"></i> <i class="fa fa-pinterest fa-2x"></i> <i class="fa fa-google-plus fa-2x"></i>#}
{#            </div>#}
{#          </div>#}

        </div><!--/col-3-->
    	<div class="col-sm-9">
            <ul class="nav ">

            <li class="nav-item">
                <li class="nav-item" {% if request.path ==  about_url %} active {% endif %} >
                    <a class="nav-link" href="about/">About</a>
                </li>
                <li class="nav-item">
                   <li class="nav-item" {% if request.path == friends_url %} active {% endif %} >
                    <a class="nav-link" href="friends/">Friends</a>
                </li>
                </li>
                <li class="nav-item {% if request.path == task_url %} active{% endif %}">
                    <a class="nav-link" href="tasks/">Tasks</a>
                </li>
                <li class="nav-item {% if request.path == task_history_url %} active {% endif %}">
                    <a class="nav-link" href="task_history/">Task History</a>
                </li>
              </ul>
        <div class="tab-content">
            <div class="container">
                {% block profilecontent %}{% endblock %}
             </div>
        </div>


          </div><!--/tab-content-->

        </div><!--/col-9-->
    </div>
{% endblock %}