accounts/urls.py
from django.conf.urls import url

# from .views import (
#
#         my_profile,
#         product_requests,
#         my_products,
#         favorites
#         )

urlpatterns = [
    #url(r'^$',my_profile , name='my_profile'),
    #url(r'^product_requests/$',product_requests , name='product_requests'),
    #url(r'^my_products/$',my_products , name='my_products'),
    #url(r'^favorites/$',favorites , name='favorites'),
    #url(r'^sent_requests/$',favorites , name='sent'),
    #url(r'^recieved_requests/$',favorites , name='recieved'),



    #rl(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
]

carts/urls.py
from django.conf.urls import url

from .views import (
   cart_home,
   cart_update,
    checkout_home,

)

urlpatterns = [

    url(r'^$', cart_home, name='home'),
    url(r'^update/$',cart_update, name='update'),
    url(r'^checkout/$',checkout_home, name='checkout'),
]

ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import home_page,about_page,contact_page,my_orders
from accounts.views import login_page, register_page,logout_view, guest_register_view
from django.conf import settings
from django.conf.urls.static import static
#from django.contrib.auth.views import LogoutView
from products.views import add_product

#from comments.views import CommentLikeToggle
from products.views import  ProductListView





urlpatterns = [
    url(r'^$',  ProductListView.as_view(), name ='home'),
    url(r'^about/$', about_page, name ='about'),
    url(r'^contact/$', contact_page, name ='contact'),
    url(r'^orders/$',my_orders, name ='my_orders'),
    # url(r'^orders/(?P<pk>\d+)/update/$', request_update, name='book_update'),
    url(r'^login/$', login_page, name ='login'),
    url(r'^register/guest$', guest_register_view, name ='guest_register'),
    url(r'^logout/$',logout_view, name ='logout'),
    url(r'^register/$', register_page, name ='register'),
    url(r'^products/',include("products.urls" , namespace='products')),
    url(r'^product_requests/',include("product_requests.urls" , namespace='product_requests')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^accounts/', include("accounts.urls", namespace='accounts')),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^admin/', admin.site.urls),
    url(r'^add_product/$', add_product, name = 'add_product'),
    url(r'^requests/', include("requests.urls", namespace='requests')),
    url(r'^profile/', include("userprofile.urls", namespace='userprofile')),
    url(r'^friends/', include("friends.urls", namespace='friends')),

]

if settings.DEBUG :
    urlpatterns = urlpatterns +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product_requests/urls.py
from django.conf.urls import url

from .views import (
        sentrequest,


        )

urlpatterns = [
    url(r'^sent/$', sentrequest, name='sentrequest'),
    ]

userprofile/urls.py
from django.conf.urls import url

from .views import (

        my_profile,
        my_tasks,
        task_requests,
        #ProfileDetailSlugView,
        friend_requests,
        my_friends,
        profile_detail,
        friend_profile_about,
        friend_profile_friends,
        friend_profile_task_history,
        friend_profile_task,

)

urlpatterns = [
    url(r'^$',my_profile , name='my_profile'),
    url(r'^my_tasks/$',my_tasks , name='my_tasks'),
    url(r'^task_requests/$',task_requests , name='task_requests'),
    url(r'^(?P<slug>[\w-]+)/$',profile_detail, name = 'profile_detail'),
    url(r'^friend_request/$',friend_requests , name='friend_requests'),
    url(r'^my_friends/$',my_friends , name='my_friends'),
    url(r'^(?P<slug>[\w-]+)/about/$',friend_profile_about, name = 'friend_profile_about'),
    url(r'^(?P<slug>[\w-]+)/tasks/$',friend_profile_task, name = 'friend_profile_task'),
    url(r'^(?P<slug>[\w-]+)/task_history/$',friend_profile_task_history, name = 'friend_profile_task_history'),
    url(r'^(?P<slug>[\w-]+)/friends/$',friend_profile_friends, name = 'friend_profile_friends'),



]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser
)
from django.contrib.auth.base_user import BaseUserManager

class UserManager(BaseUserManager):
    def create_user(self,email, full_name,password=None, is_active=True,is_staff=False, is_admin=False):
        if not email:
            raise ValueError('Users must have a valid email address')
        if not password:
            raise ValueError('Users must have a password')
        if not full_name:
            raise ValueError('Users must have a full name')
        user_obj = self.model(
            email = self.normalize_email(email),
            full_name = full_name
        )
        user_obj.staff=is_staff
        user_obj.admin = is_admin
        user_obj.active=is_active
        user_obj.set_password(password)
        user_obj.save(using=self._db)
        return user_obj

    def create_staffuser(self,email,full_name,password=None):
        user = self.create_user(
            email,
            full_name,
            password=password,
            is_staff=True

            )
        return user

    def create_superuser(self, email,full_name, password=None):
        user = self.create_user(
            email,
            full_name,
            password=password,
            is_admin=True,
            is_staff=True

        )
        return user


class User( AbstractBaseUser):
    email = models.EmailField(unique=True, max_length=255, default='noname@ug.bilkent.edu.tr')
    full_name = models.CharField(max_length = 255, null=True, blank=True)
    active = models.BooleanField(default=True) #can login
    staff = models.BooleanField(default = False)
    admin = models.BooleanField(default=False) #superuser
    timestamp = models.DateTimeField(auto_now_add=True)

    REQUIRED_FIELDS = ['full_name']
    USERNAME_FIELD = 'email'


    objects = UserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.full_name

    def get_short_name(self):
        return self.email

    def has_perm(self,perm,obj=None):
        return True

    def has_module_perms(self,app_label):
        return True

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_active(self):
        return self.active


# class Profile(models.Model):
#     user = models.ForeignKey(User)
#     #extend extra data for user profile like user image
# or create a different app

class GuestEmail(models.Model):
    email = models.EmailField()
    active = models.BooleanField(default=True)
    update = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

product_requests/models.py
from django.db import models
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from products.models import Product
# Create your models here.
#
#
User = settings.AUTH_USER_MODEL



class Product_Request(models.Model):
    sender        = models.ForeignKey(User, null=True, blank=True)
    product       = models.ForeignKey(Product, blank=True, null=True)
    reciever      = models.CharField(max_length=1200, blank=True, null=True)
    from_date     = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    till_date     = models.DateTimeField(null=True, blank=True)

    #product_owner = models.ForeignKey(Product.user, blank= True, null= True)

    def __str__(self):
        return str(self.product)

    # def clean_till_date(self):
    #     email = self.cleaned_data.get("email")
    #     if ((till_date - from_date) > 3):
    #         raise forms.ValidationError("This product cannot be shared for more than 3 days ")
    #     return email

def request_pre_save_receiver(sender, instance, *args, **kwargs):
    product_name = instance.product
    product = Product.objects.get_by_title(product_name)
    user = product.user
    instance.reciever = user


pre_save.connect(request_pre_save_receiver, sender=Product_Request)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField

User = get_user_model()

class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email','full_name',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'active', 'admin','full_name')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

class GuestForm(forms.Form):
    email = forms.EmailField()

class LoginForm(forms.Form):
    username = forms.EmailField(label='Email')
    password = forms.CharField(widget=forms.PasswordInput)



class RegisterForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email','full_name',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.active=False #send confirmation email
        if commit:
            user.save()
        return user

accounts/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, get_user_model,login
from django.utils.http import is_safe_url
from .forms import LoginForm,RegisterForm,GuestForm
from django.contrib.auth import logout
from django.contrib import messages
from .models import GuestEmail
from products.models import Product
from django.conf import settings

def guest_register_view(request):
    guest_form = GuestForm(request.POST or None)
    context = {

        "title" : "Guest Login",
        "form": guest_form
    }
    next_ = request.GET.get('next')
    next_post = request.POST.get('next')
    redirect_path = next_ or next_post or None

    if guest_form.is_valid():
        email = guest_form.cleaned_data.get("email")
        new_guest_email = GuestEmail.objects.create(email=email)
        request.session['guest_email_id'] = new_guest_email.id
        if is_safe_url(redirect_path, request.get_host()):
            return redirect(redirect_path)
        else:
            return redirect("/register/")

    return redirect("/register/")


def login_page(request):
    login_form = LoginForm(request.POST or None)
    context = {

        "title" : "Login",
        "form": login_form
    }
    next_ = request.GET.get('next')
    next_post = request.POST.get('next')
    redirect_path = next_ or next_post or None

    if login_form.is_valid():
        print(login_form.cleaned_data)
        username = login_form.cleaned_data.get("username")
        password = login_form.cleaned_data.get("password")
        user = authenticate( username=username, password=password)
        if user is not None:
            login(request, user)
            try :
                del request.session['guest_email_id']
            except:
                pass
            if is_safe_url(redirect_path, request.get_host()):
                return redirect(redirect_path)
            else:
                context['form'] = LoginForm()
                return redirect("/")
        else:
            print("Error")

    return render(request, "accounts/login_page.html", context)

User = get_user_model()

def register_page(request):
    register_form = RegisterForm(request.POST or None)
    context = {

        "title" : "Register",
        "form": register_form
    }
    if register_form.is_valid():
      register_form.save()
    #return render(request, "products/list.html", context)
    return render(request, "accounts/register_page.html", context)



def logout_view(request):
    logout(request)
    return redirect('/login/')

user = settings.AUTH_USER_MODEL
# def my_profile(request):
#     context = {}
#     return render(request,'accounts/myprofile.html', context)
# def product_requests(request):
#     context = {}
#     return render(request, 'accounts/product_requests.html', context)
# def my_products(request):
#     user = request.user
#     products = Product.objects.get_by_user(user)
#     context = {
#         'products' : products
#     }
#     return render(request,'accounts/my_products.html', context)
# def favorites(request):
#     context = {}
#     return render(request,'accounts/favorites.html', context)
# def sentrequests(request):
#     context = {}
#     return render(request,'accounts/sentrequests.html', context)
# def recievedrequests(request):
#
#     context = {}
#     return render(request,'accounts/recievedrequests.html',context)

product_requests/views.py
from django.shortcuts import render
from .models import Product_Request
from django.conf import settings
from products.models import Product
# Create your views here.

User = settings.AUTH_USER_MODEL

def recievedrequest(request):
    requests = Product_Request.objects.all()
    context = {
        'requests': requests,
    }
    return render(request,'recieved_request.html',context)


def sentrequest(request):
    requests = Product_Request.objects.filter(sender = request.user)
    for request_ in requests:
        print(request_.product.user)
    context = {
    }
    return render(request,'product_requests/recieved_request.html',context)

accounts/templates/accounts/accountsbase.html
{% extends 'base.html' %}

{% block content %}

{% url 'accounts:my_profile' as profile_url %}
{% url 'accounts:my_products' as products_url %}
{% url 'accounts:product_requests' as requests_url %}
{% url 'accounts:favorites' as favorites_url %}


    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

<!------ Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

<!------ Include the above in your HEAD tag ---------->

<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>


<hr>
<div class="container bootstrap snippet">
    <div class="row">
  		<div class="col-sm-10"><h1>User name</h1></div>
    	<div class="col-sm-2"><a href="#" class="pull-right"><img title="profile image" class="img-circle img-responsive" src="http://www.gravatar.com/avatar/28fd20ccec6865e2d5f0e1f4446eb7bf?s=100"></a></div>
    </div>
    <div class="row">
  		<div class="col-sm-3"><!--left col-->


      <div class="text-center">
        <img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="avatar img-circle img-thumbnail" alt="avatar">
        <h6>Upload a different photo...</h6>
        <input type="file" class="text-center center-block file-upload">
      </div></hr><br>


          <div class="panel panel-default">
            <div class="panel-heading">Website <i class="fa fa-link fa-1x"></i></div>
            <div class="panel-body"><a href="http://bootnipets.com">bootnipets.com</a></div>
          </div>


          <ul class="list-group">
            <li class="list-group-item text-muted">Activity <i class="fa fa-dashboard fa-1x"></i></li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Shares</strong></span> 125</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Likes</strong></span> 13</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Posts</strong></span> 37</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Followers</strong></span> 78</li>
          </ul>

          <div class="panel panel-default">
            <div class="panel-heading">Social Media</div>
            <div class="panel-body">
            	<i class="fa fa-facebook fa-2x"></i> <i class="fa fa-github fa-2x"></i> <i class="fa fa-twitter fa-2x"></i> <i class="fa fa-pinterest fa-2x"></i> <i class="fa fa-google-plus fa-2x"></i>
            </div>
          </div>

        </div><!--/col-3-->
    	<div class="col-sm-9">
            <ul class="nav nav-tabs">

                <li class="nav-item {% if request.path == profile_url %} active {% endif %}">
                    <a class="nav-link" href="{{profile_url}}">Edit Profile</a>
                </li>
                <li class="nav-item {% if request.path == products_url %} active {% endif %}">
                    <a class="nav-link" href="{{products_url}}">My Products</a>
                </li>
                <li class="nav-item {% if request.path == requests_url %} active {% endif %}">
                    <a class="nav-link" href="{{requests_url}}">Requests</a>
                </li>
                <li class="nav-item {% if request.path == favorites_url %} active {% endif %}">
                    <a class="nav-link" href="{{favorites_url}}">Favorites</a>
                </li>
              </ul>
        <div class="tab-content">
            <div class="container">
                {% block accountscontent %}{% endblock %}
             </div>
        </div>


          </div><!--/tab-content-->

        </div><!--/col-9-->
    </div>
{% endblock %}

accounts/templates/accounts/favorites.html
 {% include 'accounts/accountsbase.html'%}
    <div class="container">
        {% block accountscontent %}
            <p> THESE ARE MY FAVORITE PRODUCTS</p>
        {% endblock %}
    </div>

accounts/templates/accounts/login_page.html
{% extends 'base.html' %}

{% block content %}
     <h1>Login</h1>
    <form method="POST">{% csrf_token %}
          {{ form }}<br/>

            <button type="submit" class="btn btn-default">Submit</button>
    </form>
{% endblock %}

accounts/templates/accounts/my_products.html
  {% include 'accounts/accountsbase.html'%}
    <div class="container">
        {% block accountscontent %}
            {% for product in products %}
                  {% include 'products/snippets/card.html' with instance=product %}
            {% endfor %}
        {% endblock %}
    </div>

accounts/templates/accounts/product_requests.html
  {% include 'accounts/accountsbase.html'%}
{% url 'accounts:sent' as sentrequests_url %}
{% url 'accounts:recieved' as recievedrequests_url %}
    <div class="container">
        {% block accountscontent %}
            	<div class="col-sm-9">
            <ul class="nav ">

                 <li class="nav-item {% if request.path == sentrequests_url %} active {% endif %}">
                     <a class="nav-link" href="{{sentrequests_url}}">Sent Requests</a>
                 </li>
                  <li class="nav-item {% if request.path == recievedrequests_url %} active {% endif %}">
                     <a class="nav-link" href="{{recievedrequests_url}}">Recieved Requests </a>
                 </li>
              </ul>
        {% endblock %}
    </div>

accounts/templates/accounts/recievedrequests.html
  {% include 'accounts/accountsbase.html'%}
    <div class="container">
        {% block accountscontent %}
            <p> THESE ARE RECIEVED REQUESTS OF MY PRODUCTS</p>
        {% endblock %}
    </div>

accounts/templates/accounts/register_page.html
{% extends 'base.html' %}

{% block content %}
    <h1>Register</h1>
    <form method="POST">{% csrf_token %}
          {{ form }}<br/>

        <button type="submit" class="btn btn-default">Submit</button>
    </form>
    {% if messages %}
        <br/>
        <br/>
        <div class="col -sm-6 col -sm-offset-3" >
        {% for message in messages %}
            <p {% if message.tags %} class="alert alert-success" {% endif %}>{{ message }}</p>
        {% endfor %}
        </div>
    {% endif %}
{% endblock %}

accounts/templates/accounts/sentrequests.html
  {% include 'accounts/accountsbase.html'%}
    <div class="container">
        {% block accountscontent %}
            <p> THESE ARE PRODUCT REQUESTS SENT</p>
        {% endblock %}
    </div>