carts/urls.py
from django.conf.urls import url

from .views import (
   cart_home,
   cart_update,
    checkout_home,

)

urlpatterns = [

    url(r'^$', cart_home, name='home'),
    url(r'^update/$',cart_update, name='update'),
    url(r'^checkout/$',checkout_home, name='checkout'),
]

ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import home_page,about_page,contact_page,my_orders
from accounts.views import login_page, register_page,logout_view, guest_register_view
from django.conf import settings
from django.conf.urls.static import static
#from django.contrib.auth.views import LogoutView
from products.views import add_product

#from comments.views import CommentLikeToggle
from products.views import  ProductListView





urlpatterns = [
    url(r'^$',  ProductListView.as_view(), name ='home'),
    url(r'^about/$', about_page, name ='about'),
    url(r'^contact/$', contact_page, name ='contact'),
    url(r'^orders/$',my_orders, name ='my_orders'),
    # url(r'^orders/(?P<pk>\d+)/update/$', request_update, name='book_update'),
    url(r'^login/$', login_page, name ='login'),
    url(r'^register/guest$', guest_register_view, name ='guest_register'),
    url(r'^logout/$',logout_view, name ='logout'),
    url(r'^register/$', register_page, name ='register'),
    url(r'^products/',include("products.urls" , namespace='products')),
    url(r'^product_requests/',include("product_requests.urls" , namespace='product_requests')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^accounts/', include("accounts.urls", namespace='accounts')),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^admin/', admin.site.urls),
    url(r'^add_product/$', add_product, name = 'add_product'),
    url(r'^requests/', include("requests.urls", namespace='requests')),
    url(r'^profile/', include("userprofile.urls", namespace='userprofile')),
    url(r'^friends/', include("friends.urls", namespace='friends')),

]

if settings.DEBUG :
    urlpatterns = urlpatterns +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url

from .views import (
        ProductListView,
        ProductDetailSlugView,
        ProductLikeToggle,




        )

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/like/$', ProductLikeToggle.as_view(), name='like-toggle'),





]

requests/urls.py
from django.conf.urls import url

from .views import (

    requests_home,
    friend_request,
    PastRequests

)

urlpatterns = [

    url(r'^$', requests_home, name='home'),
    url(r'^friend_request/$', friend_request, name='friend_request'),
    url(r'^past_request/$', PastRequests.as_view(), name='past_requests'),
    url(r'^past_request_cancel/(?P<id>\d+)/$', PastRequests.as_view(), name='past_request_cancel'),
]

products/models.py
import random
import os
from django.db import models
from django.db.models.signals import pre_save
from ecommerce.utils import unique_slug_generator
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.conf import settings
from accounts.models import User





def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    # print(instance)
    #print(filename)
    new_filename = random.randint(1,3910209312)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "products/{new_filename}/{final_filename}".format(
            new_filename=new_filename,
            final_filename=final_filename
            )

class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

    def featured(self):
        return self.filter(featured=True, active=True)

    def search(self, query):
        lookups = (Q(title__icontains=query) |
                  Q(description__icontains=query) |
                  Q(price__icontains=query) |
                  Q(tag__title__icontains=query)
                  )
        # tshirt, t-shirt, t shirt, red, green, blue,
        return self.filter(lookups).distinct()

    def get_userp_by_title(self, title):
        qs = self.get_queryset().filter(title=title)  # Product.objects == self.get_queryset()
        product = qs.first()
        userp_qs = product.userp
        userp = userp_qs.first()
        return userp


class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()


    def featured(self): #Product.objects.featured()
        return self.get_queryset().featured()

    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id) # Product.objects == self.get_queryset()
        if qs.count() == 1:
            return qs.first()
        return None

    def search(self, query):
        return self.get_queryset().active().search(query)

    def create_product(self,title, description, destination, tip):
        return Product.objects.create(title=title, description=description, destination= destination, tip=tip)

    def get_by_userp(self, userp):
        user_id = userp.id
        qs = self.get_queryset().filter(userp = user_id)
        return qs
        #first find the id of the userp
        #userp = userp.id
        #userp_qs = []
        #userp_qs.append(userp)
        #qs = self.get_queryset().filter(userp = userp_qs) # Product.objects == self.get_queryset()
        #return type(qs)

    def get_by_title(self,title):
        qs = self.get_queryset().filter(title = title) # Product.objects == self.get_queryset()
        product = qs.first()
        return product

    def get_userp_by_title(self,title):
        qs = self.get_queryset().filter(title = title) # Product.objects == self.get_queryset()
        product = qs.first()
        userp_qs = product.userp
        userp = userp_qs.first()
        return userp

    def get_liked_products_by_user(self, user):
        like_product_qs = []
        #user_id = user.id
        all_product_qs = Product.objects.all()
        for product in all_product_qs:
            like_user_qs = product.likes.all()
            if user in like_user_qs :
                like_product_qs.append(product)
        return like_product_qs
        


class Product(models.Model):
    userp           = models.ManyToManyField(User, blank=True, related_name='product_owner')
    title           = models.CharField(max_length=120)
    slug            = models.SlugField(blank=True, unique=True)
    description     = models.TextField()
    price           = models.DecimalField(decimal_places=2, max_digits=20, default=0.00)
    image           = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    likes           = models.ManyToManyField(User, blank=True, related_name='post_likes')
    featured        = models.BooleanField(default=False)
    active          = models.BooleanField(default=True)
    timestamp       = models.DateTimeField(auto_now_add=True)
    is_digital      = models.BooleanField(default=False) # User Library
    destination     = models.CharField(max_length=120, null=True, blank=True)
    tip             = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    views           = models.ManyToManyField(User, blank=True, related_name='product_viewers')
    objects = ProductManager()

    def get_absolute_url(self):
        #return "/products/{slug}/".format(slug=self.slug)
        return reverse("products:detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    @property
    def name(self):
        return self.title


    def get_downloads(self):
        qs = self.productfile_set.all()
        return qs

    def get_like_url(self):
        return reverse("products:like-toggle", kwargs={'slug': self.slug})

    # def userp(self):
    #     return self.owner


# def product_pre_save_user(sender, instance, *args, **kwargs):
#     instance.user = User


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(product_pre_save_receiver, sender=Product)
#pre_save.connect(product_pre_save_user, sender=Product)


def upload_product_file_loc(instance, filename):
    slug = instance.product.slug
    #id_ = 0
    id_ = instance.id
    if id_ is None:
        Klass = instance.__class__
        qs = Klass.objects.all().order_by('-pk')
        if qs.exists():
            id_ = qs.first().id + 1
        else:
            id_ = 0
    if not slug:
        slug = unique_slug_generator(instance.product)
    location = "product/{slug}/{id}/".format(slug=slug, id=id_)
    return location + filename #"path/to/filename.mp4"

products/forms.py
from django import forms
from django.contrib.auth import get_user_model



User = get_user_model()



class AddProductForm(forms.Form):

    product_title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Product title"

            }
        )
    )
    product_description = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Describe specifics your product"

            }
        )
    )
    destination = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Where can this task be done/ product be found :"

            }
        )
    )
    tip = forms.DecimalField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "How much are you offering to complete this task : "

            }
        )
    )
    # image = forms.ImageField()



class TaskForm(forms.Form):
    CHOICES=[('accept','accept'),
             ('reject','reject')]

    task_status = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)

products/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.views.generic import ListView, DetailView, View
from django.shortcuts import render, get_object_or_404, redirect
from carts.models import Cart
from .models import Product
from .forms import AddProductForm
from django.contrib import messages
from django.views.generic import RedirectView
from comments.models import Comment
from django.contrib.contenttypes.models import ContentType
from accounts.models import User
from django.views.generic.edit import FormMixin
from django import forms
from django.http import HttpResponseForbidden
from django.core.urlresolvers import reverse, reverse_lazy



class ProductFeaturedListView(ListView):
    template_name = "products/list.html"

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all().featured()


class ProductFeaturedDetailView(DetailView):
    queryset = Product.objects.all().featured()
    template_name = "products/featured-detail.html"

    # def get_queryset(self, *args, **kwargs):
    #     request = self.request
    #     return Product.objects.featured()


class ProductListView(ListView):
    template_name = "products/list.html"

    # def get_context_data(self, *args, **kwargs):
    #     context = super(ProductListView, self).get_context_data(*args, **kwargs)
    #     print(context)
    #     return context

    def get_context_data(self, *args, **kwargs):
        context = super(ProductListView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all()

class ProductLikeToggle(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        slug = self.kwargs.get('slug')
        obj = get_object_or_404(Product, slug=slug)
        url_ = obj.get_absolute_url()
        user = self.request.user
        if user.is_authenticated():
            if user in obj.likes.all():
                obj.likes.remove(user)
            else:
                obj.likes.add(user)
        return url_


def product_list_view(request):
    queryset = Product.objects.all()
    context = {
        'object_list': queryset
    }
    return render(request, "products/list.html", context)


class ProductDetailSlugView(DetailView):


    queryset = Product.objects.all()
    template_name = "products/detail.html"




    def get_context_data(self, *args, **kwargs):

        context = super(ProductDetailSlugView, self).get_context_data(*args, **kwargs)
        product_userp_list = User.objects.all()
        userp = product_userp_list[0].full_name
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        context['userp'] = userp
        return context




    def get_object(self, *args, **kwargs):
        request = self.request


        slug = self.kwargs.get('slug')

                # instance = get_object_or_404(Product, slug=slug, active=True)
        try:
            instance = Product.objects.get(slug=slug, active=True)
        except Product.DoesNotExist:
            raise Http404("Not found..")
        except Product.MultipleObjectsReturned:
            qs = Product.objects.filter(slug=slug, active=True)
            instance = qs.first()
            view_lst = []
            view_lst.append(request.user)
            instance.views = view_lst
        except:
            raise Http404("Uhhmmm ")
        return instance






def product_detail_view(request, pk=None, *args, **kwargs):
    # instance = Product.objects.get(pk=pk, featured=True) #id
    # instance = get_object_or_404(Product, pk=pk, featured=True)
    # try:
    #     instance = Product.objects.get(id=pk)
    # except Product.DoesNotExist:
    #     print('no product here')
    #     raise Http404("Product doesn't exist")
    # except:
    #     print("huh?")

    instance = Product.objects.get_by_id(pk)
    if instance is None:
        raise Http404("Product doesn't exist")
    # print(instance)
    # qs  = Product.objects.filter(id=pk)

    # #print(qs)
    # if qs.exists() and qs.count() == 1: # len(qs)
    #     instance = qs.first()
    # else:
    #     raise Http404("Product doesn't exist")

    context = {
        'object': instance
    }
    return render(request, "products/detail.html", context)

def add_product(request):
    add_product_form = AddProductForm(request.POST)

    context = {
        'page_title' : "Add Product",
        'form' : add_product_form,

    }
    if add_product_form.is_valid():
        print(add_product_form)
        title = add_product_form.cleaned_data.get('product_title')
        description = add_product_form.cleaned_data.get('product_description')
        destination = add_product_form.cleaned_data.get('destination')
        tip = add_product_form.cleaned_data.get('tip')
        # image = add_product_form.cleaned_data.get('image')
        new_product = Product.objects.create_product(title, description, destination, tip)
        messages.success(request, "Product created successfully")
        print(new_product)
        print("Product creation successful")
    return render(request, 'products/add_product.html', context)

# def add_comment_view(request):
#     add_comment_form = AddCommentForm(request.POST)
#     context = {
#
#         'form' : add_comment_form
#     }
#     if add_comment_form.is_valid():
#         comment_user = request.user
#         comment_text = add_comment_form.cleaned_data.get('comment_text')
#         new_comment = Comment.objects.create(comment_user, comment_text)
#         messages.success(request, "Comment added successfully")
#         print(new_comment)


    #     print("Product creation successful")
    # return render(request, 'products/detail.html', context)


# class TaskForm(forms.Form):
#     CHOICES=[('accept','accept'),
#              ('reject','reject')]
#
#     task_status = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)
#
#
# class ProductDetailSlugView(FormMixin, DetailView):
#     model = Product
#     form_class = TaskForm
#     template_name = "products/detail.html"
#
#     def get_success_url(self):
#         if kwargs != None:
#             return reverse_lazy('products/')
#
#
#     def get_context_data(self, **kwargs):
#         context = super(ProductDetailSlugView, self).get_context_data(**kwargs)
#         context['form'] = self.get_form()
#         return context
#
#     def post(self, request, *args, **kwargs):
#         if not request.user.is_authenticated():
#             return HttpResponseForbidden()
#         self.object = self.get_object()
#         form = self.get_form()
#         if form.is_valid():
#             return self.form_valid(form)
#         else:
#             return self.form_invalid(form)
#
#     def form_valid(self, form):
#         # Here, we would record the user's interest using the message
#         # passed in form.cleaned_data['message']
#         return super(ProductDetailSlugView, self).form_valid(form)
#         def form_valid(self, form):
#             # Here, we would record the user's interest using the message
#             # passed in form.cleaned_data['message']
#             return super(ProductDetailSlugView, self).form_valid(form)

products/templates/products/add_product.html
{% extends 'base.html' %}

{% block content %}
    <h1>Add Task</h1>
    <form enctype="multipart/form-data" method="POST" >{% csrf_token %}
          {{ form }}<br/>

        <button type="submit" class="btn btn-default" value="Create Task">Submit</button>
    </form>

    {% if messages %}
        <br/>
        <br/>
        <div class="col -sm-6 col -sm-offset-3" >
        {% for message in messages %}
            <p {% if message.tags %} class="alert alert-success" {% endif %}>{{ message }}</p>
        {% endfor %}
        </div>
    {% endif %}
{% endblock %}

products/templates/products/detail.html
{% extends "base.html" %}


{% block content %}


    <div class='row'>
        <div class='col-12 col-md-6'>
                <h1>{{ object.title }}</h1>
                by <h4>{{userp}}</h4>
                {{ object.timestamp|timesince }} ago
                {{ object.description|linebreaks }}<br/>
                <p> {% if object.likes.count == 0 %} 0 {% else %}{{ object.likes.count }}{% endif %}<a href="{{ object.get_like_url }}">&nbsp;&nbsp;&nbsp;Like</a></p>
                {% if object.image %}
                    <img src='{{ object.image.url }}' class='img-fluid' />

                {% endif %}
        </div>
    <div clas="col-12 col-md-6">
        {% include 'products/snippets/update-cart.html' with product=object cart=cart %}

    </div>

    {% if messages %}
        <br/>
        <br/>
        <div class="col -sm-6 col -sm-offset-3" >
        {% for message in messages %}
            <p {% if message.tags %} class="alert alert-success" {% endif %}>{{ message }}</p>
        {% endfor %}
        </div>
    {% endif %}


{% endblock %}

products/templates/products/featured-detail.html
{{ obj.title }}<br/>
{{ obj.description }}<br/>
{% if obj.image %}
    <img src="{{ obj.image.url }}" class="img-fluid"/>
{% endif %}

products/templates/products/list.html
{% extends 'base.html' %}

{% block past-requests %}
     <div class="past-request-container card text-white bg-secondary mb-3" id="past-requests"></div>
{% endblock %}

{% block content %}
       <div class="row">
    {% for obj in object_list %}
        <div class="col">
        {% include 'products/snippets/card.html' with instance=obj %}
        {%  if forloop.counter|divisibleby:1%}
        </div></div><div class="row"><div class="col-12"><hr/></div>
        {% else %}
        </div>
        {% endif %}
    {% endfor %}

   </div>
{% endblock %}

{% block seperate_js %}
<script>
function getPastRequests(limit, offset){
    var url = '{% url "requests:past_requests" %}';
    url += '?limit=' + limit + '&offset=' + offset;

    $.ajax({
        type:'GET',
        url: url,
        data:{
            action: 'get',
        },
        success:function(json){
            console.log('success');
            console.log(json);

            let past_req = "";
            json.forEach(function (item) {
                past_req += `<div class="past-request-item">
                                <div class="past-request-item product product-name">${item.product_name}</div>
                                <div class="past-request-item product-status">${item.status}</div>
                                <button class="button past-request-btn" id="past-product-${item.id}">Cancel</div>{% csrf_token %}
                            </div>`
            });
            $("#past-requests").html(past_req);
        },
        error : function(xhr,errmsg,err) {
            let errors = JSON.parse(xhr.responseText).errors;
            console.log(errors);
            console.log('failiure');
            $("#past-requests").html("");

        }
    });
}

     $(document).ready( function(){
        getPastRequests(5, 0);
    });


     $(document).on('click', '.past-request-btn', function(event){
        event.preventDefault();
        var post_dom_id = (this.id).split('-');
        var post_id = Number(post_dom_id[post_dom_id.length - 1]);
        console.log(post_id);
        var url = '{% url "requests:past_request_cancel" id=0 %}'.replace(0, post_id);
        $.ajax({
            type:'POST',
            url:url,
            data:{
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json){
                console.log(json);
                console.log('success');
                getPastRequests(5, 0);
            },
            error : function(xhr,errmsg,err) {
                 console.log('err');
                 }
        });
    });

</script>
{% endblock %}

products/templates/products/test.html
{% extends "base.html" %}


{% block content %}

    {{ text }}


{% endblock %}